language: c
sudo: false

env:
    global: PYTHON_VERSION=3.7
            CONDA_DEPENDENCIES="numpy scipy matplotlib pyqt>=5.9 coverage pytest pytest-cov flake8 pygments traits traitsui pyface"
            PIP_DEPENDENCIES="codecov pytest-sugar pytest-faulthandler nibabel imageio imageio-ffmpeg"
            DISPLAY=:99.0

matrix:
    include:
        # Full
        - os: linux
          addons:
            apt:
              packages:
                - mencoder

        # 2.7, no mencoder
        - os: linux
          env: PYTHON_VERSION=2.7
               CONDA_DEPENDENCIES="numpy scipy matplotlib coverage pytest pytest-cov flake8 mayavi"
               PIP_DEPENDENCIES="codecov pytest-sugar faulthandler pytest-faulthandler nibabel imageio imageio-ffmpeg"

        # OSX
        - os: osx

# Setup anaconda
before_install:
    # Rvm overrides cd with a function so that it can hook into it to run
    # some scripts, see https://github.com/travis-ci/travis-ci/issues/8703
    - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
        unset -f cd;
      fi;
    - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
        echo "Starting Xvfb...";
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render;
      fi;
    - git clone https://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - if [ "$PYTHON_VERSION" != "2.7" ]; then
        pip install vtk;
        pip install mayavi;
      fi;

install:
    - python setup.py build
    - python setup.py install
    - SRC_DIR=$(pwd)

before_script:
    # Let's create a (fake) display on Travis, and let's use a funny resolution
    - cd ~
    - wget --quiet http://faculty.washington.edu/larsoner/fsaverage_min.zip
    - mkdir subjects
    - cd subjects
    - unzip ../fsaverage_min.zip
    - cd ..
    - export SUBJECTS_DIR="${PWD}/subjects"

script:
    - cd ${SRC_DIR}
    - pytest surfer --cov=surfer -v
    - make flake

after_success:
    - codecov
