language: c
sudo: false
dist: xenial
services:
    - xvfb
env:
    global: PYTHON_VERSION=3.8
            CONDA_DEPENDENCIES="numpy scipy matplotlib pyqt coverage pytest pytest-cov flake8 pygments traits traitsui pyface"
            PIP_DEPENDENCIES="codecov pytest-sugar pytest-faulthandler nibabel imageio imageio-ffmpeg"
            DISPLAY=:99.0
            SUBJECTS_DIR=~/subjects

matrix:
    include:
        # Full
        - os: linux
          addons:
            apt:
              packages:
                - mencoder
                - libosmesa6
                - libglx-mesa0
                - libopengl0
                - libglx0
                - libdbus-1-3

        # 3.5, no mencoder
        - os: linux
          env: PYTHON_VERSION=3.6
               CONDA_DEPENDENCIES="numpy scipy matplotlib coverage pytest pytest-cov flake8"
               PIP_DEPENDENCIES="codecov pytest-sugar nibabel imageio imageio-ffmpeg"

        # OSX
        - os: osx

# Setup anaconda
before_install:
    # Rvm overrides cd with a function so that it can hook into it to run
    # some scripts, see https://github.com/travis-ci/travis-ci/issues/8703
    - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
        unset -f cd;
      fi;
    - git clone https://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - if [ "${PYTHON_VERSION}" == "3.6" ]; then
        pip install --only-binary ":all:" "vtk<9";
        pip install mayavi;
      else
        pip install --only-binary ":all:" -f "https://vtk.org/download" "vtk>=9";
        pip install https://github.com/enthought/mayavi/zipball/master;
      fi;
    - mkdir -p $SUBJECTS_DIR
    - pip install "https://api.github.com/repos/mne-tools/mne-python/zipball/master";
    - python -c "import mne; mne.datasets.fetch_fsaverage(verbose=True)"

install:
    - python setup.py build
    - python setup.py install
    - SRC_DIR=$(pwd)

script:
    - cd ${SRC_DIR}
    - pytest surfer --cov=surfer -v
    - make flake

after_success:
    - codecov
