language: c
sudo: false
# This list of requirements is way overkill, but it helps ensure we
# actually load a usable config (it works for MNE-Python)
env:
    global: PYTHON_VERSION=2.7
            DISPLAY=:99.0
            CONDA_DEPENDENCIES="numpy scipy matplotlib pandas scikit-learn h5py pillow statsmodels mayavi"
            PIP_DEPENDENCIES="coverage coveralls nose-timer nibabel flake8 imageio"

matrix:
    include:
        # Full (Linux, 2.7)
        - os: linux
          addons:
            apt:
              packages:
                - mencoder

        # Minimal (no mencoder)
        - os: linux

        # OSX (disabled because it's slow)
        - os: osx

# Setup anaconda
before_install:
    - git clone https://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - conda install ffmpeg -c conda-forge

install:
    - python setup.py build
    - python setup.py install
    - SRC_DIR=$(pwd)

before_script:
    # Let's create a (fake) display on Travis, and let's use a funny resolution
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render;
      fi;
    - cd ~
    - wget --quiet http://faculty.washington.edu/larsoner/fsaverage_min.zip
    - mkdir subjects
    - cd subjects
    - unzip ../fsaverage_min.zip
    - cd ..
    - export SUBJECTS_DIR="${PWD}/subjects"

script:
    - cd ${SRC_DIR}
    - nosetests --with-timer --timer-top-n 10
    - make flake

after_success:
    # Need to run from source dir to exectue "git" commands
    - coveralls
