language: c
sudo: false

env:
    global: PYTHON_VERSION=2.7
            DISPLAY=:99.0

matrix:
    include:
        # Full (Linux, 3.6)
        - os: linux
          env: CONDA_ENVIRONMENT="environment.yml"
          addons:
            apt:
              packages:
                - mencoder

        # Full (Linux, 2.7)
        - os: linux
          env: CONDA_DEPENDENCIES="numpy scipy matplotlib mayavi flake8 pytest pytest-cov coverage"
               PIP_DEPENDENCIES="codecov nibabel imageio"
          addons:
            apt:
              packages:
                - mencoder

        # Minimal (no mencoder)
        - os: linux
          env: CONDA_DEPENDENCIES="numpy scipy matplotlib mayavi flake8 pytest pytest-cov coverage"
               PIP_DEPENDENCIES="codecov nibabel"

        # OSX
        - os: osx
          env: CONDA_DEPENDENCIES="numpy scipy matplotlib mayavi flake8 pytest pytest-cov coverage"
               PIP_DEPENDENCIES="codecov nibabel imageio"

# Setup anaconda
before_install:
    # Rvm overrides cd with a function so that it can hook into it to run
    # some scripts, see https://github.com/travis-ci/travis-ci/issues/8703
    - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
        unset -f cd;
      fi;
    - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
        echo "Starting Xvfb...";
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render;
      fi;
    - git clone https://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh

install:
    - python setup.py build
    - python setup.py install
    - SRC_DIR=$(pwd)

before_script:
    # Let's create a (fake) display on Travis, and let's use a funny resolution
    - cd ~
    - wget --quiet http://faculty.washington.edu/larsoner/fsaverage_min.zip
    - mkdir subjects
    - cd subjects
    - unzip ../fsaverage_min.zip
    - cd ..
    - export SUBJECTS_DIR="${PWD}/subjects"
    - if [[ $PIP_DEPENDENCIES == *"imageio"* ]] || [ ! -z "$CONDA_ENVIRONMENT" ]; then
        python -c "import imageio; imageio.plugins.ffmpeg.download()";
      fi

script:
    - cd ${SRC_DIR}
    - pytest surfer
    - make flake

after_success:
    - codecov
