environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "pip install numpy scipy matplotlib nose pillow pytest pytest-cov pytest-faulthandler coverage imageio imageio-ffmpeg codecov pyqt5==5.9"
  - "pip install traits traitsui pyface vtk https://github.com/enthought/mayavi/archive/master.zip nibabel"
  - "powershell make/get_fsaverage.ps1"
  - "python setup.py develop"
  - "SET SUBJECTS_DIR=%CD%\\subjects"
  - "ls %CD%\\subjects"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  # Run the project tests
  - "pytest surfer --cov=surfer -v"

on_success:
  - "codecov"
