environment:
  global:
      PYTHON: "C:\\conda"
      MINICONDA_VERSION: "latest"
      CONDA_DEPENDENCIES: "numpy scipy matplotlib nose pillow sphinx pytest pytest-cov coverage traits traitsui pyface vtk"
      PIP_DEPENDENCIES: "mayavi nibabel imageio git+git://github.com/sphinx-gallery/sphinx-gallery.git numpydoc codecov"
  matrix:
      - PYTHON_VERSION: "3.6"
        PYTHON_ARCH: "64"

install:
  - "git clone git://github.com/astropy/ci-helpers.git"
  - "powershell ci-helpers/appveyor/install-miniconda.ps1"
  - "powershell make/get_fsaverage.ps1"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "activate test"
  - "python setup.py develop"
  - "conda install ffmpeg -c conda-forge"
  - "SET SUBJECTS_DIR=%CD%\\subjects"
  - "ls %CD%\\subjects"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  # Run the project tests
  - "pytest surfer"
  - cd doc
  # The Makefile doesn't work directly on Windows PowerShell because of
  # slashes (but will work e.g. in Msys-git), so for now do these manually
  # make html-noplot
  - sphinx-build -D plot_gallery=0 -b html -d _build\doctrees . _build\html
  - cd ..


on_success:
  - "codecov"

artifacts:
  - path: doc\_build\html
