name: mne
channels:
- defaults
dependencies:
- python>=3.6
- pip
- mkl
- numpy
- scipy
- matplotlib
- pyqt>=5.9
- vtk>=8
- nose
- coverage
- pytest
- pytest-cov
- flake8
- pygments
- traits
- traitsui
- pyface
- pip:
  - mayavi
  - nibabel
  - pytest-sugar
  - pytest-faulthandler
  - imageio
  - codecov
