version: 2
jobs:
    build:
      docker:
        - image: circleci/python:3.6-stretch
      steps:
        # Get our data and merge with upstream
        - checkout
        - run: echo $(git log -1 --pretty=%B) | tee gitlog.txt
        - run: echo ${CI_PULL_REQUEST//*pull\//} | tee merge.txt
        - run:
           command: |
             if [[ $(cat merge.txt) != "" ]]; then
               echo "Merging $(cat merge.txt)";
               git pull --ff-only origin "refs/pull/$(cat merge.txt)/merge";
             fi

        # Load our data
        - restore_cache:
            keys:
              - data-cache

        - run: echo "export SUBJECTS_DIR=$HOME/subjects" >> $BASH_ENV
        - run: echo "export DISPLAY=:99" >> $BASH_ENV
        - run: /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset;
        # Get latest Anaconda running
        - run: echo "export PATH=~/miniconda/envs/mne/bin:~/miniconda/bin:$PATH" >> $BASH_ENV
        - run:
            command: |
              wget -q http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O ~/miniconda.sh;
              chmod +x ~/miniconda.sh;
              ~/miniconda.sh -b -p ~/miniconda;
        - run:
            command: |
              conda update --yes --quiet conda;
              conda env create --quiet -f environment.yml;
        # This is a CircleCI-specific fix -- for some reason 5.9.2 is problematic
        # here but not on Travis, we get:
        #
        #     libgcc_s.so.1 must be installed for pthread_cancel to work
        #     Aborted
        #
        - run: pip install --upgrade --no-deps pyqt5>=5.10
        - run: python -c "from mayavi import mlab; import matplotlib.pyplot as plt; mlab.figure(); plt.figure()"
        - run: python setup.py develop
        - run: echo $SUBJECTS_DIR
        - run:
            command: |
              if [ ! -d $SUBJECTS_DIR ]; then
                mkdir $SUBJECTS_DIR;
                cd $SUBJECTS_DIR;
                wget http://faculty.washington.edu/larsoner/fsaverage_min.zip;
                unzip fsaverage_min.zip;
                rm fsaverage_min.zip;
              fi;
        - run: ls $SUBJECTS_DIR
        - run:
            command: |
              if [[ $(cat build.txt) == "html_dev" ]] || [[ $(cat build.txt) == "html_stable" ]]; then
                SUBJECTS_DIR=~/mne_data/MNE-sample-data/subjects python -c "import mne; mne.datasets._download_all_example_data()";
              fi;
        - run: cd doc && sphinx-build -D plot_gallery=1 -D sphinx_gallery_conf.filename_pattern=^\(\(?\!plot_fmri_activation_volume\|plot_morphometry\|plot_label\|plot_probabilistic_label\|plot_resting_correlations\|plot_transparent_brain\|rotate_animation\|save_movie\|save_views\).\)*\$ -b html -d _build/doctrees . _build/html

        - store_artifacts:
            path: doc/_build/html/
            destination: html

        - save_cache:
            key: data-cache
            paths:
              - "~/subjects"
